name: Compile

on:
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build system setup
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget

      - name: Update the feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure using config diff file
        run: |
          cp diffconfig .config
          make defconfig

      - name: Build the firmware image
        run: make -j $(($(nproc)+1)) download world

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # name: Artifact
          path: ./bin/targets/
